# Generated by Django 4.0.2 on 2022-04-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomplete_emptying', models.IntegerField(null=True)),
                ('frequency', models.IntegerField(null=True)),
                ('intermittency', models.IntegerField(null=True)),
                ('urgency', models.IntegerField(null=True)),
                ('weak_stream', models.IntegerField(null=True)),
                ('straining', models.IntegerField(null=True)),
                ('nocturia', models.IntegerField(null=True)),
                ('quality_of_life', models.IntegerField(null=True)),
                ('total_score', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
