# Generated by Django 4.0.2 on 2022-04-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='frequency',
            field=models.IntegerField(choices=[(0, 'Not at all'), (1, 'Less than 1 time in 5'), (2, 'Less than half the time'), (3, 'About half the time'), (4, 'More than half the time'), (5, 'Almost always')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='incomplete_emptying',
            field=models.IntegerField(choices=[(0, 'Not at all'), (1, 'Less than 1 time in 5'), (2, 'Less than half the time'), (3, 'About half the time'), (4, 'More than half the time'), (5, 'Almost always')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='intermittency',
            field=models.IntegerField(choices=[(0, 'Not at all'), (1, 'Less than 1 time in 5'), (2, 'Less than half the time'), (3, 'About half the time'), (4, 'More than half the time'), (5, 'Almost always')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='nocturia',
            field=models.IntegerField(choices=[(0, 'Not at all'), (1, 'Less than 1 time in 5'), (2, 'Less than half the time'), (3, 'About half the time'), (4, 'More than half the time'), (5, 'Almost always')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='quality_of_life',
            field=models.IntegerField(choices=[(0, 'Not at all'), (1, 'Less than 1 time in 5'), (2, 'Less than half the time'), (3, 'About half the time'), (4, 'More than half the time'), (5, 'Almost always')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='straining',
            field=models.IntegerField(choices=[(0, 'Not at all'), (1, 'Less than 1 time in 5'), (2, 'Less than half the time'), (3, 'About half the time'), (4, 'More than half the time'), (5, 'Almost always')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='total_score',
            field=models.IntegerField(blank=True, choices=[(0, 'Not at all'), (1, 'Less than 1 time in 5'), (2, 'Less than half the time'), (3, 'About half the time'), (4, 'More than half the time'), (5, 'Almost always')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='urgency',
            field=models.IntegerField(choices=[(0, 'Not at all'), (1, 'Less than 1 time in 5'), (2, 'Less than half the time'), (3, 'About half the time'), (4, 'More than half the time'), (5, 'Almost always')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='weak_stream',
            field=models.IntegerField(choices=[(0, 'Not at all'), (1, 'Less than 1 time in 5'), (2, 'Less than half the time'), (3, 'About half the time'), (4, 'More than half the time'), (5, 'Almost always')], default=0, null=True),
        ),
    ]
