# Generated by Django 4.0.2 on 2022-04-16 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0002_alter_survey_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='survey',
            name='frequency',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='incomplete_emptying',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='intermittency',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='nocturia',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='quality_of_life',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='straining',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='total_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='urgency',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='weak_stream',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
