# Generated by Django 4.0.2 on 2022-04-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_survey_user_alter_survey_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
