# Generated by Django 4.0.2 on 2022-04-20 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_survey_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='id',
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survey',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
