# Generated by Django 4.0.2 on 2022-04-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_survey_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
