# Generated by Django 4.0.2 on 2022-04-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_survey_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='event_change',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
